//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Frotz.rc
//
#define IDR_MANIFEST                    1
#define IDR_FROTZ                       100
#define IDR_TOOLBAR                     101
#define IDI_INFOCOM                     200
#define IDI_Z1                          201
#define IDI_Z2                          202
#define IDI_Z3                          203
#define IDI_Z4                          204
#define IDI_Z5                          205
#define IDI_Z6                          206
#define IDI_Z7                          207
#define IDI_Z8                          208
#define IDI_ZLB                         209
#define IDI_TZ                          220
#define IDI_TZ1                         221
#define IDI_TZ2                         222
#define IDI_TZ3                         223
#define IDI_TZ4                         224
#define IDI_TZ5                         225
#define IDI_TZ6                         226
#define IDI_TZ7                         227
#define IDI_TZ8                         228
#define IDB_GFXFONT                     300
#define IDB_FROTZ                       301
#define IDD_ABOUT                       400
#define IDD_SCROLLBACK                  401
#define IDD_LOADGAME                    402
#define IDD_ABOUTGAME                   403
#define IDD_OPTIONS_DISPLAY             410
#define IDD_OPTIONS_INTERPRETER         411
#define IDD_OPTIONS_STARTUP             412
#define IDD_OPTIONS_SPEECH              413
#define IDC_PROP_FONT                   1000
#define IDC_FIXED_FONT                  1001
#define IDC_FONT_SIZE                   1002
#define IDC_TEXT_COLOUR                 1003
#define IDC_BACK_COLOUR                 1004
#define IDC_TERP_NUMBER                 1005
#define IDC_ERRORS                      1007
#define IDC_IGNORE_RUNTIME              1008
#define IDC_EXPAND                      1009
#define IDC_TANDY                       1010
#define IDC_COPY                        1011
#define IDC_TEXT                        1012
#define IDC_LOGO                        1013
#define IDC_QUETZAL                     1014
#define IDC_FAST_SCROLL                 1015
#define IDC_LEFT_MARGIN                 1016
#define IDC_RIGHT_MARGIN                1017
#define IDC_MORE_PROMPT                 1018
#define IDC_REGISTER_FILETYPES          1019
#define IDC_INFO                        1020
#define IDC_BORDER                      1021
#define IDC_WRAP_SCRIPT                 1022
#define IDC_SHOW_IFICTION               1023
#define IDC_LABEL_IFICTION              1024
#define IDC_STARTUP                     1025
#define IDC_USERNAME                    1026
#define IDC_SPEAK                       1027
#define IDC_VOICE                       1028
#define IDC_SPEECH_RATE                 1029
#define IDS_BLORB_GLULX                 10000
#define IDS_BLORB_NOEXEC                10001
#define IDS_MORE                        10002
#define IDS_HIT_KEY_EXIT                10003
#define IDS_TITLE                       10004
#define IDS_FATAL                       10005
#define IDS_ZCODE_FILTER                10006
#define IDS_ZCODE_TITLE                 10007
#define IDS_SAVE_FILTER                 10008
#define IDS_SAVE_TITLE                  10009
#define IDS_RESTORE_TITLE               10010
#define IDS_SCRIPT_FILTER               10011
#define IDS_SCRIPT_TITLE                10012
#define IDS_RECORD_FILTER               10013
#define IDS_RECORD_TITLE                10014
#define IDS_PLAYBACK_TITLE              10015
#define IDS_AUX_FILTER                  10016
#define IDS_SAVE_AUX_TITLE              10017
#define IDS_LOAD_AUX_TITLE              10018
#define IDS_FROTZ                       10019
#define IDS_FAIL_DIRECTSOUND            10020
#define IDS_FULLSCREEN                  10022
#define IDS_ABOUT_INFO                  10023
#define IDS_QUETZAL                     10024
#define IDS_OPTIONS                     10025
#define IDS_LINK                        10026
#define IDS_HELP_FAILED                 10027
#define IDS_INFOCOM_BLORB1              10028
#define IDS_INFOCOM_BLORB2              10029
#define IDS_INFOCOM_BLORB3              10030
#define ID_HOT_PLAYBACK                 32771
#define ID_HOT_RECORD                   32772
#define ID_HOT_SEED                     32773
#define ID_HOT_UNDO                     32774
#define ID_HOT_RESTART                  32775
#define ID_HOT_QUIT                     32776
#define ID_HOT_DEBUG                    32777
#define ID_HOT_HELP                     32778
#define ID_VIEW_OPTIONS                 32780
#define ID_VIEW_SCROLLBACK              32781
#define ID_FILE_STOP                    32782
#define ID_APP_ABOUT_GAME               32783
#define ID_LINKS_FROTZ                  32800
#define ID_LINKS_ARCHIVE                32801
#define ID_LINKS_ZCODE                  32802
#define ID_LINKS_IFDB                   32803
#define ID_LINKS_INTFICTION             32804
#define ID_LINKS_PLANETIF               32805
#define ID_LINKS_IFWIKI                 32806
#define ID_LINKS_IFCOMP                 32807
#define ID_LINKS_IFMUD                  32808
#define ID_LINKS_INFORM7                32809
#define ID_LINKS_INFORM6                32810
#define ID_FULLSCREEN                   32900
#define ID_INDICATOR_TIME               32901
#define ID_INDICATOR_ZCODE              32902
#define ID_RL_BEGIN                     32903
#define ID_RL_END                       32904
#define ID_RL_DEL                       32905
#define ID_RL_BACK                      32906
#define ID_RL_FORWARD                   32907
#define ID_RL_RUBOUT                    32908
#define ID_RL_KILL                      32909

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        404
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1030
#define _APS_NEXT_SYMED_VALUE           100
#endif
#endif
